### ISSUE TITLE
Ingress 1.79.0 is missing some of the artifact resources

### ISSUE THREAD

**Issue by evshiron** [DeviateFish/ingress-model-viewer#3]
Ingress newer than 1.78.0 is stripping out old artifact resources, and MUFG Capsule is added in recently version so an asset merge is needed. And the AssetManager doesn't handle errors properly, thus resulting in rendering nothing.

**Comment by DeviateFish** [comment]
Yeah, I need to readdress the `AssetManager` in the next release.  On my list:  adding incremental asset loading (so you don't need to give it a full manifest, and let it handle merging of manifests, etc), as well as better error handling.

I'll bump this up in priority, especially with the removal of even more assets from the client.  I think that will also come with the removal of the jarvis shards from this repo, too, since I'm not really a fan of having assets that aren't mine stored in a public repo (so grab them while you can).

This might turn into a pretty complicated release, but that's okay.  It's good that you bring this up, I've been meaning to fix it for some time, but I just keep working around it, instead.

**Comment by DeviateFish** [comment]
Done in v0.17.0
