### ISSUE TITLE
Hosted?

### ISSUE THREAD

**Issue by ryantheleach** [DeviateFish/ingress-model-viewer#35]
Is this hosted anywhere? I think I used to check it out on the default github pages routing, but now it seems that it's inaccessible due to being assigned the docs directory.

**Comment by DeviateFish** [comment]
There's [actual documentation](https://deviatefish.github.io/ingress-model-viewer/) up on the github pages urls, now.  I wasn't aware that it was hosted in that way before--or at least I don't think it ever was.

I don't plan on hosting this anywhere because that would require also hosting the `.obj` files found in the apks, which aren't mine.  So, for legal reasons and whatnot, you'll have to pull it down and host it locally.  From there, just drop the apk's `assets` folder into the root can enjoy

**Comment by ryantheleach** [comment]
I think I must be thinking of the polymer test.

**Comment by DeviateFish** [comment]
Ah, you might be.  I need to update that to a newer version of... everything, really.

**Comment by rjwut** [comment]
The documentation is great. It would be helpful to have sample code, as well.

**Comment by DeviateFish** [comment]
@rjwut It's on the list.  There are some "demos" in the `demos` folder, but they aren't well documented or anything.  The best one (so far) is probably `sandbox.html`... the most complex is definitely `snapshots.html` + `capture.js`

**Comment by rjwut** [comment]
Yeah, but unfortunately, they don't appear to work right now. For example, running sandbox.html triggers the error "IMV.Engine is not a constructor." Perhaps these demos were written for an older version of IMV and haven't been updated to reflect your changes?

**Comment by DeviateFish** [comment]
@rjwut `sandbox.html` was actually what I used to generate that animation of the new items that's floating around...  So maybe there's a step missing?  How are you serving `sandbox.html`?

Try starting it with `npm run serve` and seeing what happens?

**Comment by rjwut** [comment]
I was running it under a node server, but I realized something I had done wrong. I corrected the issue I was experiencing, but things are still not working right. Here is what happens when I attempt to view each demo page:

**clean-slate.html**: Blank white page. Console shows no errors.

**portal-test.html**: A small red portal appears on the screen, then resonators appear one by one around it. Two of the resonators have no connecting beams; the rest do, but they are red instead of matching the resonator color, and extend far past the actual location of the resonator. The size of the portal does not increase with each deployed resonator, as they do in the actual application. After all resonators are deployed, the portal turns blue.

**globe.html** An interactive globe (with a red link between North America and Europe) appears as expected. However, strange white artifacts appear around the lower edge of the globe as you rotate it.

**sandbox.html**: Blank black page. Console shows no errors.

**animation-test.html**: Blank white page, console shows the error "IMV.Utilities.AssetLoader is not a constructor."

**link-test.html**: Blank white page. Console shows no errors.

**snapshots.html**: Blank white page, console shows the error "IMV.Utilities.AssetLoader is not a constructor."

**Comment by DeviateFish** [comment]
Ah, that sounds much more like what I would expect.

* `clean-slate.html` - Basically what you'd expect... pretty much a clean slate, requires manual boot-up of the engine and renderer, etc.
* `portal-test.html` - hasn't been updated in a while, so not surprising it's broken.
* `globe.html` - The port of the WebGL Globe seems to have a couple known issues: the "hole in the ozone layer" that appears when you view the globe from directly above the north (or maybe south) pole.  The other artifacts are likely due to the "atmosphere" shader.
* `sandbox.html` - This one should be working, and should boot up and show the orbiting transmuters.  I'll look into why there are no error messages... Do you have an `assets` folder from the latest apk?
* `animation-test.html` - Apparently I haven't updated this one since I refactored asset loading.
* `link-test.html` - Definitely needs an update
* `snapshots.html` - same as `animation-test.html`.

I'll look into cleaning up or fixing these demos.  I have a tendency of fixing whichever one helps me test new changes, but not the others... so they get updated in a very sporadic fashion.

**Comment by rjwut** [comment]
Answering your question from `sandbox.html`: Yes, I did extract the `assets` folder from the latest APK. (I imagine I would have gotten a bunch of 404 errors in `portal-test.html` if I hadn't.) I checked the Network tab in the Chrome developer console and it does seem to be loading various assets, but nothing appears on the page.

**Comment by DeviateFish** [comment]
Interesting.  You have the latest version of the `master` branch, too?  It used to be a demo that I think needed some manual starting, but I just changed that in my most recent commits.

**Comment by rjwut** [comment]
Aha, that was the problem. I was using the latest release, not master. When I downloaded master and tried it out, `sandbox.html` worked.

**Comment by DeviateFish** [comment]
Ah okay. I guess I forgot to cut a new release! I'll add that to my list.
